#!/bin/bash
# This script restores the iptables state and ensures kernel forwarding is active.

echo "Applying Firewall Rules..."

# Load iptables rules via here-doc
iptables-restore <<EOF
# Generated by iptables-save v1.8.11 (nf_tables) on Wed Mar 18 02:14:44 2026
*raw
:PREROUTING ACCEPT [9144132:14878963805]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -d 172.18.0.2/32 ! -i br-c10e951d4035 -j DROP
COMMIT
# Completed on Wed Mar 18 02:14:44 2026
# Generated by iptables-save v1.8.11 (nf_tables) on Wed Mar 18 02:14:44 2026
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [142:58141]
:OUTPUT ACCEPT [0:0]
:DOCKER - [0:0]
:DOCKER-BRIDGE - [0:0]
:DOCKER-CT - [0:0]
:DOCKER-FORWARD - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
-A FORWARD -i enp1s0 -o enp5s0 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i enp1s0 -o enp5s0 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
COMMIT
# Completed on Wed Mar 18 02:14:44 2026
# Generated by iptables-save v1.8.11 (nf_tables) on Wed Mar 18 02:14:44 2026
*nat
:PREROUTING ACCEPT [39305:13082299]
:INPUT ACCEPT [17039:1283396]
:OUTPUT ACCEPT [23226:1957280]
:POSTROUTING ACCEPT [3975:355393]
:DOCKER - [0:0]
-A POSTROUTING -o enp5s0 -j MASQUERADE
COMMIT
# Completed on Wed Mar 18 02:14:44 2026
EOF

# Ensure the Kernel is actually forwarding packets
sysctl -w net.ipv4.ip_forward=1

echo "Firewall and Routing updated."

# Trigger sync at Wed Mar 18 02:55:17 AM IST 2026
