#comment from arch to server via github + systemd
# DNS Settings
port=53
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=1.1.1.1

# Interface Settings
interface=enp1s0
interface=lo
bind-interfaces
listen-address=127.0.0.1,192.168.1.1

# DHCP Settings
dhcp-range=192.168.1.50,192.168.1.150,12h
dhcp-option=option:router,192.168.1.1
dhcp-option=option:dns-server,192.168.1.1
dhcp-authoritative

